/**
 * Design Tokens CSS Generator
 *
 * IMPORTANT: This file only contains what Tailwind JIT CANNOT generate:
 * - CSS Variables (:root)
 * - Custom theme color classes (primary, accent, background, foreground, muted)
 * - Custom font families
 * - Opacity variants for custom colors
 * - Hover/Focus states for custom colors
 *
 * All standard Tailwind utilities are generated by JIT in the CSS export route.
 */

import type { DesignVariables } from '@/types/cms'

/**
 * Generates CSS for custom colors from Design Variables
 */
function generateCustomColorsCSS(customColors: Record<string, string>): string {
  if (!customColors || Object.keys(customColors).length === 0) {
    return ''
  }

  let css = ''

  // CSS Variables
  css += ':root {\n'
  for (const [name, value] of Object.entries(customColors)) {
    css += `  --color-custom-${name}: ${value};\n`
  }
  css += '}\n\n'

  // Utility Classes for each custom color
  for (const [name] of Object.entries(customColors)) {
    css += `/* Custom Color: ${name} */\n`
    css += `.bg-${name} { background-color: var(--color-custom-${name}) !important; }\n`
    css += `.text-${name} { color: var(--color-custom-${name}) !important; }\n`
    css += `.border-${name} { border-color: var(--color-custom-${name}) !important; }\n`
    css += `.hover\\:bg-${name}:hover { background-color: var(--color-custom-${name}) !important; }\n`
    css += `.hover\\:text-${name}:hover { color: var(--color-custom-${name}) !important; }\n`
    css += `.hover\\:border-${name}:hover { border-color: var(--color-custom-${name}) !important; }\n`
    css += `\n`
  }

  return css
}

/**
 * Generates CSS for all design variables
 * Used in editor and export
 */
export function generateDesignTokensCSS(designVars: DesignVariables | null): string {
  const colors = designVars?.colors
  const typography = designVars?.typography
  const spacing = designVars?.spacing
  const borders = designVars?.borders
  const gradients = designVars?.gradients
  const customColors = designVars?.customColors || {}

  // Default values
  const brandPrimary = colors?.brand?.primary || '#3b82f6'
  const brandPrimaryHover = colors?.brand?.primaryHover || '#2563eb'
  const brandSecondary = colors?.brand?.secondary || '#64748b'
  const brandAccent = colors?.brand?.accent || '#8b5cf6'

  const neutralBackground = colors?.neutral?.background || '#ffffff'
  const neutralForeground = colors?.neutral?.foreground || '#0f172a'
  const neutralMuted = colors?.neutral?.muted || '#f1f5f9'
  const neutralBorder = colors?.neutral?.border || '#e2e8f0'

  const semanticSuccess = colors?.semantic?.success || '#22c55e'
  const semanticWarning = colors?.semantic?.warning || '#f59e0b'
  const semanticError = colors?.semantic?.error || '#ef4444'
  const semanticInfo = colors?.semantic?.info || '#3b82f6'

  const fontHeading = typography?.fontHeading || 'Inter'
  const fontBody = typography?.fontBody || 'Inter'
  const fontMono = typography?.fontMono || 'JetBrains Mono'

  const radiusDefault = borders?.radius?.default || '0.5rem'
  const radiusLg = borders?.radius?.lg || '0.75rem'

  // Convert hex to RGB for opacity support
  const hexToRgb = (hex: string): string => {
    const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex)
    return result
      ? `${parseInt(result[1], 16)}, ${parseInt(result[2], 16)}, ${parseInt(result[3], 16)}`
      : '59, 130, 246'
  }

  return `
/* ============================================
   BASE RESET (Tailwind Preflight)
   ============================================ */

/* Alpine.js x-cloak - hide elements until Alpine initializes */
[x-cloak] {
  display: none !important;
}

*, ::before, ::after {
  box-sizing: border-box;
  border-width: 0;
  border-style: solid;
}

html, body {
  margin: 0;
  padding: 0;
  width: 100%;
}

button, [role="button"] {
  cursor: pointer;
}

a {
  color: inherit;
  text-decoration: inherit;
}

h1, h2, h3, h4, h5, h6 {
  font-size: inherit;
  font-weight: inherit;
  margin: 0;
}

p, blockquote, figure, pre {
  margin: 0;
}

ul, ol {
  margin: 0;
  padding: 0;
  list-style: none;
}

button, input, optgroup, select, textarea {
  font-family: inherit;
  font-size: 100%;
  font-weight: inherit;
  line-height: inherit;
  color: inherit;
  margin: 0;
  padding: 0;
}

img, svg, video, canvas, audio, iframe, embed, object {
  display: block;
  vertical-align: middle;
}

img, video {
  max-width: 100%;
  height: auto;
}

[hidden] {
  display: none;
}

/* ============================================
   CSS VARIABLES (Theme Tokens)
   ============================================ */

:root {
  /* Brand Colors */
  --color-brand-primary: ${brandPrimary};
  --color-brand-primary-hover: ${brandPrimaryHover};
  --color-brand-secondary: ${brandSecondary};
  --color-brand-accent: ${brandAccent};

  /* Brand Colors RGB (for opacity) */
  --color-brand-primary-rgb: ${hexToRgb(brandPrimary)};
  --color-brand-secondary-rgb: ${hexToRgb(brandSecondary)};
  --color-brand-accent-rgb: ${hexToRgb(brandAccent)};

  /* Neutral Colors */
  --color-neutral-background: ${neutralBackground};
  --color-neutral-foreground: ${neutralForeground};
  --color-neutral-muted: ${neutralMuted};
  --color-neutral-border: ${neutralBorder};

  /* Neutral Colors RGB (for opacity) */
  --color-neutral-foreground-rgb: ${hexToRgb(neutralForeground)};
  --color-neutral-background-rgb: ${hexToRgb(neutralBackground)};

  /* Semantic Colors */
  --color-semantic-success: ${semanticSuccess};
  --color-semantic-warning: ${semanticWarning};
  --color-semantic-error: ${semanticError};
  --color-semantic-info: ${semanticInfo};

  /* Typography */
  --font-heading: '${fontHeading}', system-ui, sans-serif;
  --font-body: '${fontBody}', system-ui, sans-serif;
  --font-mono: '${fontMono}', monospace;

  /* Border Radius */
  --radius-default: ${radiusDefault};
  --radius-lg: ${radiusLg};
  --radius-sm: 0.25rem;
  --radius-xl: 1rem;
  --radius-2xl: 1.5rem;
  --radius-full: 9999px;

  /* Spacing */
  --spacing-section: ${spacing?.scale?.section || '5rem'};
  --spacing-container: ${spacing?.containerWidths?.xl || '1280px'};

  /* Shadows */
  --shadow-sm: 0 1px 2px 0 rgb(0 0 0 / 0.05);
  --shadow-md: 0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1);
  --shadow-lg: 0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1);
  --shadow-xl: 0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1);

  /* Transitions */
  --transition-fast: 150ms ease;
  --transition-normal: 250ms ease;
  --transition-slow: 350ms ease;
}

${gradients?.primary?.enabled ? `
/* Gradient */
:root {
  --gradient-primary: linear-gradient(
    ${gradients.primary.direction?.replace('to-', 'to ') || 'to right'},
    ${gradients.primary.from || brandPrimary}
    ${gradients.primary.via ? `, ${gradients.primary.via}` : ''}
    , ${gradients.primary.to || brandAccent}
  );
}
` : ''}

/* ============================================
   CUSTOM THEME COLORS (JIT cannot generate these)
   ============================================ */

/* Background Colors */
.bg-primary { background-color: var(--color-brand-primary); }
.bg-primary-hover { background-color: var(--color-brand-primary-hover); }
.bg-secondary { background-color: var(--color-brand-secondary); }
.bg-accent { background-color: var(--color-brand-accent); }
.bg-background { background-color: var(--color-neutral-background); }
.bg-muted { background-color: var(--color-neutral-muted); }
.bg-foreground { background-color: var(--color-neutral-foreground); }
.bg-border { background-color: var(--color-neutral-border); }

/* Aliases for long class names */
.bg-neutral-background { background-color: var(--color-neutral-background); }
.bg-neutral-foreground { background-color: var(--color-neutral-foreground); }
.bg-neutral-muted { background-color: var(--color-neutral-muted); }
.bg-neutral-border { background-color: var(--color-neutral-border); }
.bg-brand-primary { background-color: var(--color-brand-primary); }
.bg-brand-secondary { background-color: var(--color-brand-secondary); }
.bg-brand-accent { background-color: var(--color-brand-accent); }

/* Background with Opacity (common values) */
.bg-primary\\/5 { background-color: rgba(${hexToRgb(brandPrimary)}, 0.05); }
.bg-primary\\/10 { background-color: rgba(${hexToRgb(brandPrimary)}, 0.1); }
.bg-primary\\/20 { background-color: rgba(${hexToRgb(brandPrimary)}, 0.2); }
.bg-primary\\/30 { background-color: rgba(${hexToRgb(brandPrimary)}, 0.3); }
.bg-primary\\/40 { background-color: rgba(${hexToRgb(brandPrimary)}, 0.4); }
.bg-primary\\/50 { background-color: rgba(${hexToRgb(brandPrimary)}, 0.5); }
.bg-primary\\/60 { background-color: rgba(${hexToRgb(brandPrimary)}, 0.6); }
.bg-primary\\/70 { background-color: rgba(${hexToRgb(brandPrimary)}, 0.7); }
.bg-primary\\/80 { background-color: rgba(${hexToRgb(brandPrimary)}, 0.8); }
.bg-primary\\/90 { background-color: rgba(${hexToRgb(brandPrimary)}, 0.9); }

.bg-accent\\/5 { background-color: rgba(${hexToRgb(brandAccent)}, 0.05); }
.bg-accent\\/10 { background-color: rgba(${hexToRgb(brandAccent)}, 0.1); }
.bg-accent\\/20 { background-color: rgba(${hexToRgb(brandAccent)}, 0.2); }
.bg-accent\\/30 { background-color: rgba(${hexToRgb(brandAccent)}, 0.3); }
.bg-accent\\/40 { background-color: rgba(${hexToRgb(brandAccent)}, 0.4); }
.bg-accent\\/50 { background-color: rgba(${hexToRgb(brandAccent)}, 0.5); }
.bg-accent\\/60 { background-color: rgba(${hexToRgb(brandAccent)}, 0.6); }
.bg-accent\\/70 { background-color: rgba(${hexToRgb(brandAccent)}, 0.7); }
.bg-accent\\/80 { background-color: rgba(${hexToRgb(brandAccent)}, 0.8); }
.bg-accent\\/90 { background-color: rgba(${hexToRgb(brandAccent)}, 0.9); }

.bg-foreground\\/5 { background-color: rgba(${hexToRgb(neutralForeground)}, 0.05); }
.bg-foreground\\/10 { background-color: rgba(${hexToRgb(neutralForeground)}, 0.1); }
.bg-foreground\\/20 { background-color: rgba(${hexToRgb(neutralForeground)}, 0.2); }
.bg-foreground\\/30 { background-color: rgba(${hexToRgb(neutralForeground)}, 0.3); }
.bg-foreground\\/40 { background-color: rgba(${hexToRgb(neutralForeground)}, 0.4); }
.bg-foreground\\/50 { background-color: rgba(${hexToRgb(neutralForeground)}, 0.5); }
.bg-foreground\\/60 { background-color: rgba(${hexToRgb(neutralForeground)}, 0.6); }
.bg-foreground\\/70 { background-color: rgba(${hexToRgb(neutralForeground)}, 0.7); }
.bg-foreground\\/80 { background-color: rgba(${hexToRgb(neutralForeground)}, 0.8); }
.bg-foreground\\/90 { background-color: rgba(${hexToRgb(neutralForeground)}, 0.9); }

.bg-background\\/5 { background-color: rgba(${hexToRgb(neutralBackground)}, 0.05); }
.bg-background\\/10 { background-color: rgba(${hexToRgb(neutralBackground)}, 0.1); }
.bg-background\\/20 { background-color: rgba(${hexToRgb(neutralBackground)}, 0.2); }
.bg-background\\/30 { background-color: rgba(${hexToRgb(neutralBackground)}, 0.3); }
.bg-background\\/40 { background-color: rgba(${hexToRgb(neutralBackground)}, 0.4); }
.bg-background\\/50 { background-color: rgba(${hexToRgb(neutralBackground)}, 0.5); }
.bg-background\\/60 { background-color: rgba(${hexToRgb(neutralBackground)}, 0.6); }
.bg-background\\/70 { background-color: rgba(${hexToRgb(neutralBackground)}, 0.7); }
.bg-background\\/80 { background-color: rgba(${hexToRgb(neutralBackground)}, 0.8); }
.bg-background\\/90 { background-color: rgba(${hexToRgb(neutralBackground)}, 0.9); }

.bg-muted\\/5 { background-color: rgba(${hexToRgb(neutralMuted)}, 0.05); }
.bg-muted\\/10 { background-color: rgba(${hexToRgb(neutralMuted)}, 0.1); }
.bg-muted\\/20 { background-color: rgba(${hexToRgb(neutralMuted)}, 0.2); }
.bg-muted\\/30 { background-color: rgba(${hexToRgb(neutralMuted)}, 0.3); }
.bg-muted\\/40 { background-color: rgba(${hexToRgb(neutralMuted)}, 0.4); }
.bg-muted\\/50 { background-color: rgba(${hexToRgb(neutralMuted)}, 0.5); }
.bg-muted\\/60 { background-color: rgba(${hexToRgb(neutralMuted)}, 0.6); }
.bg-muted\\/70 { background-color: rgba(${hexToRgb(neutralMuted)}, 0.7); }
.bg-muted\\/80 { background-color: rgba(${hexToRgb(neutralMuted)}, 0.8); }
.bg-muted\\/90 { background-color: rgba(${hexToRgb(neutralMuted)}, 0.9); }

/* Gradient Colors */
.from-primary { --tw-gradient-from: var(--color-brand-primary); }
.from-accent { --tw-gradient-from: var(--color-brand-accent); }
.from-background { --tw-gradient-from: var(--color-neutral-background); }
.from-foreground { --tw-gradient-from: var(--color-neutral-foreground); }

.to-primary { --tw-gradient-to: var(--color-brand-primary); }
.to-accent { --tw-gradient-to: var(--color-brand-accent); }
.to-background { --tw-gradient-to: var(--color-neutral-background); }
.to-transparent { --tw-gradient-to: transparent; }

/* Text Colors */
.text-primary { color: var(--color-brand-primary); }
.text-secondary { color: var(--color-brand-secondary); }
.text-accent { color: var(--color-brand-accent); }
.text-foreground { color: var(--color-neutral-foreground); }
.text-muted { color: var(--color-neutral-muted); }
.text-background { color: var(--color-neutral-background); }
.text-border { color: var(--color-neutral-border); }

/* Text Aliases */
.text-neutral-foreground { color: var(--color-neutral-foreground); }
.text-neutral-background { color: var(--color-neutral-background); }
.text-neutral-muted { color: var(--color-neutral-muted); }
.text-brand-primary { color: var(--color-brand-primary); }
.text-brand-secondary { color: var(--color-brand-secondary); }
.text-brand-accent { color: var(--color-brand-accent); }

/* Text with Opacity */
.text-primary\\/10 { color: rgba(${hexToRgb(brandPrimary)}, 0.1); }
.text-primary\\/20 { color: rgba(${hexToRgb(brandPrimary)}, 0.2); }
.text-primary\\/30 { color: rgba(${hexToRgb(brandPrimary)}, 0.3); }
.text-primary\\/40 { color: rgba(${hexToRgb(brandPrimary)}, 0.4); }
.text-primary\\/50 { color: rgba(${hexToRgb(brandPrimary)}, 0.5); }
.text-primary\\/60 { color: rgba(${hexToRgb(brandPrimary)}, 0.6); }
.text-primary\\/70 { color: rgba(${hexToRgb(brandPrimary)}, 0.7); }
.text-primary\\/80 { color: rgba(${hexToRgb(brandPrimary)}, 0.8); }
.text-primary\\/90 { color: rgba(${hexToRgb(brandPrimary)}, 0.9); }

.text-accent\\/10 { color: rgba(${hexToRgb(brandAccent)}, 0.1); }
.text-accent\\/20 { color: rgba(${hexToRgb(brandAccent)}, 0.2); }
.text-accent\\/30 { color: rgba(${hexToRgb(brandAccent)}, 0.3); }
.text-accent\\/40 { color: rgba(${hexToRgb(brandAccent)}, 0.4); }
.text-accent\\/50 { color: rgba(${hexToRgb(brandAccent)}, 0.5); }
.text-accent\\/60 { color: rgba(${hexToRgb(brandAccent)}, 0.6); }
.text-accent\\/70 { color: rgba(${hexToRgb(brandAccent)}, 0.7); }
.text-accent\\/80 { color: rgba(${hexToRgb(brandAccent)}, 0.8); }
.text-accent\\/90 { color: rgba(${hexToRgb(brandAccent)}, 0.9); }

.text-foreground\\/10 { color: rgba(${hexToRgb(neutralForeground)}, 0.1); }
.text-foreground\\/20 { color: rgba(${hexToRgb(neutralForeground)}, 0.2); }
.text-foreground\\/30 { color: rgba(${hexToRgb(neutralForeground)}, 0.3); }
.text-foreground\\/40 { color: rgba(${hexToRgb(neutralForeground)}, 0.4); }
.text-foreground\\/50 { color: rgba(${hexToRgb(neutralForeground)}, 0.5); }
.text-foreground\\/60 { color: rgba(${hexToRgb(neutralForeground)}, 0.6); }
.text-foreground\\/70 { color: rgba(${hexToRgb(neutralForeground)}, 0.7); }
.text-foreground\\/80 { color: rgba(${hexToRgb(neutralForeground)}, 0.8); }
.text-foreground\\/90 { color: rgba(${hexToRgb(neutralForeground)}, 0.9); }

.text-muted\\/10 { color: rgba(${hexToRgb(neutralMuted)}, 0.1); }
.text-muted\\/20 { color: rgba(${hexToRgb(neutralMuted)}, 0.2); }
.text-muted\\/30 { color: rgba(${hexToRgb(neutralMuted)}, 0.3); }
.text-muted\\/40 { color: rgba(${hexToRgb(neutralMuted)}, 0.4); }
.text-muted\\/50 { color: rgba(${hexToRgb(neutralMuted)}, 0.5); }
.text-muted\\/60 { color: rgba(${hexToRgb(neutralMuted)}, 0.6); }
.text-muted\\/70 { color: rgba(${hexToRgb(neutralMuted)}, 0.7); }
.text-muted\\/80 { color: rgba(${hexToRgb(neutralMuted)}, 0.8); }
.text-muted\\/90 { color: rgba(${hexToRgb(neutralMuted)}, 0.9); }

/* Border Colors */
.border-primary { border-color: var(--color-brand-primary) !important; }
.border-secondary { border-color: var(--color-brand-secondary) !important; }
.border-accent { border-color: var(--color-brand-accent) !important; }
.border-border { border-color: var(--color-neutral-border) !important; }
.border-foreground { border-color: var(--color-neutral-foreground) !important; }
.border-muted { border-color: var(--color-neutral-muted) !important; }

/* Border with Opacity */
.border-primary\\/10 { border-color: rgba(${hexToRgb(brandPrimary)}, 0.1); }
.border-primary\\/20 { border-color: rgba(${hexToRgb(brandPrimary)}, 0.2); }
.border-primary\\/30 { border-color: rgba(${hexToRgb(brandPrimary)}, 0.3); }
.border-primary\\/50 { border-color: rgba(${hexToRgb(brandPrimary)}, 0.5); }

.border-border\\/10 { border-color: rgba(${hexToRgb(neutralBorder)}, 0.1); }
.border-border\\/20 { border-color: rgba(${hexToRgb(neutralBorder)}, 0.2); }
.border-border\\/30 { border-color: rgba(${hexToRgb(neutralBorder)}, 0.3); }
.border-border\\/50 { border-color: rgba(${hexToRgb(neutralBorder)}, 0.5); }

.border-foreground\\/10 { border-color: rgba(${hexToRgb(neutralForeground)}, 0.1); }
.border-foreground\\/20 { border-color: rgba(${hexToRgb(neutralForeground)}, 0.2); }
.border-foreground\\/30 { border-color: rgba(${hexToRgb(neutralForeground)}, 0.3); }
.border-foreground\\/50 { border-color: rgba(${hexToRgb(neutralForeground)}, 0.5); }

/* Font Families */
.font-heading { font-family: var(--font-heading); }
.font-body { font-family: var(--font-body); }
.font-mono { font-family: var(--font-mono); }

/* Border Radius (using CSS vars) */
.rounded { border-radius: var(--radius-default); }
.rounded-sm { border-radius: var(--radius-sm); }
.rounded-lg { border-radius: var(--radius-lg); }
.rounded-xl { border-radius: var(--radius-xl); }
.rounded-2xl { border-radius: var(--radius-2xl); }
.rounded-full { border-radius: var(--radius-full); }

/* Shadows (using CSS vars) */
.shadow-sm { box-shadow: var(--shadow-sm); }
.shadow-md { box-shadow: var(--shadow-md); }
.shadow-lg { box-shadow: var(--shadow-lg); }
.shadow-xl { box-shadow: var(--shadow-xl); }

/* ============================================
   HOVER STATES (for custom colors)
   ============================================ */

.hover\\:bg-primary:hover { background-color: var(--color-brand-primary) !important; }
.hover\\:bg-primary-hover:hover { background-color: var(--color-brand-primary-hover) !important; }
.hover\\:bg-secondary:hover { background-color: var(--color-brand-secondary) !important; }
.hover\\:bg-accent:hover { background-color: var(--color-brand-accent) !important; }
.hover\\:bg-foreground:hover { background-color: var(--color-neutral-foreground) !important; }
.hover\\:bg-background:hover { background-color: var(--color-neutral-background) !important; }
.hover\\:bg-muted:hover { background-color: var(--color-neutral-muted) !important; }

.hover\\:text-primary:hover { color: var(--color-brand-primary) !important; }
.hover\\:text-secondary:hover { color: var(--color-brand-secondary) !important; }
.hover\\:text-accent:hover { color: var(--color-brand-accent) !important; }
.hover\\:text-foreground:hover { color: var(--color-neutral-foreground) !important; }
.hover\\:text-background:hover { color: var(--color-neutral-background) !important; }
.hover\\:text-muted:hover { color: var(--color-neutral-muted) !important; }

.hover\\:border-primary:hover { border-color: var(--color-brand-primary) !important; }
.hover\\:border-secondary:hover { border-color: var(--color-brand-secondary) !important; }
.hover\\:border-accent:hover { border-color: var(--color-brand-accent) !important; }
.hover\\:border-foreground:hover { border-color: var(--color-neutral-foreground) !important; }
.hover\\:border-muted:hover { border-color: var(--color-neutral-muted) !important; }

.hover\\:shadow-sm:hover { box-shadow: var(--shadow-sm); }
.hover\\:shadow-md:hover { box-shadow: var(--shadow-md); }
.hover\\:shadow-lg:hover { box-shadow: var(--shadow-lg); }
.hover\\:shadow-xl:hover { box-shadow: var(--shadow-xl); }

/* Group Hover */
.group:hover .group-hover\\:text-primary { color: var(--color-brand-primary); }
.group:hover .group-hover\\:text-accent { color: var(--color-brand-accent); }
.group:hover .group-hover\\:text-foreground { color: var(--color-neutral-foreground); }
.group:hover .group-hover\\:bg-primary { background-color: var(--color-brand-primary); }
.group:hover .group-hover\\:bg-accent { background-color: var(--color-brand-accent); }

/* ============================================
   FOCUS STATES
   ============================================ */

.focus\\:ring-primary:focus { --tw-ring-color: var(--color-brand-primary); }
.focus\\:border-primary:focus { border-color: var(--color-brand-primary); }
.focus\\:border-accent:focus { border-color: var(--color-brand-accent); }

/* ============================================
   CUSTOM UTILITIES
   ============================================ */

/* Scrolled state (for header) */
.scrolled {
  background-color: var(--color-neutral-background);
  box-shadow: var(--shadow-md);
}

/* Screen Reader Only */
.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border-width: 0;
}

/* Animation Keyframes */
@keyframes spin {
  to { transform: rotate(360deg); }
}
@keyframes ping {
  75%, 100% { transform: scale(2); opacity: 0; }
}
@keyframes pulse {
  50% { opacity: .5; }
}
@keyframes bounce {
  0%, 100% { transform: translateY(-25%); animation-timing-function: cubic-bezier(0.8,0,1,1); }
  50% { transform: translateY(0); animation-timing-function: cubic-bezier(0,0,0.2,1); }
}

.animate-spin { animation: spin 1s linear infinite; }
.animate-ping { animation: ping 1s cubic-bezier(0, 0, 0.2, 1) infinite; }
.animate-pulse { animation: pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite; }
.animate-bounce { animation: bounce 1s infinite; }

/* ============================================
   CUSTOM COLORS (from Site Setup)
   ============================================ */
${generateCustomColorsCSS(customColors)}
`.trim()
}

/**
 * Generates Google Fonts Import URL
 */
export function generateGoogleFontsLink(designVars: DesignVariables | null): string {
  const fonts = new Set<string>()

  if (designVars?.typography?.fontHeading) {
    fonts.add(designVars.typography.fontHeading)
  }
  if (designVars?.typography?.fontBody) {
    fonts.add(designVars.typography.fontBody)
  }
  if (designVars?.typography?.fontMono) {
    fonts.add(designVars.typography.fontMono)
  }

  if (fonts.size === 0) return ''

  const fontParams = Array.from(fonts)
    .map(font => `family=${encodeURIComponent(font)}:wght@300;400;500;600;700;800`)
    .join('&')

  return `https://fonts.googleapis.com/css2?${fontParams}&display=swap`
}

/**
 * Applies CSS variables to a DOM element (for editor/iframe)
 */
export function applyDesignTokensToElement(
  element: HTMLElement,
  designVars: DesignVariables | null
): void {
  const colors = designVars?.colors
  const typography = designVars?.typography

  // Brand colors
  element.style.setProperty('--color-brand-primary', colors?.brand?.primary || '#3b82f6')
  element.style.setProperty('--color-brand-primary-hover', colors?.brand?.primaryHover || '#2563eb')
  element.style.setProperty('--color-brand-secondary', colors?.brand?.secondary || '#64748b')
  element.style.setProperty('--color-brand-accent', colors?.brand?.accent || '#8b5cf6')

  // Neutral colors
  element.style.setProperty('--color-neutral-background', colors?.neutral?.background || '#ffffff')
  element.style.setProperty('--color-neutral-foreground', colors?.neutral?.foreground || '#0f172a')
  element.style.setProperty('--color-neutral-muted', colors?.neutral?.muted || '#f1f5f9')
  element.style.setProperty('--color-neutral-border', colors?.neutral?.border || '#e2e8f0')

  // Typography
  element.style.setProperty('--font-heading', `'${typography?.fontHeading || 'Inter'}', system-ui, sans-serif`)
  element.style.setProperty('--font-body', `'${typography?.fontBody || 'Inter'}', system-ui, sans-serif`)
}
